services:
  backend:
    build: 
      context: . 
      dockerfile: Dockerfile 
    ports: 
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    
  db:
    image: postgres:15
    restart: "no"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: