services:
  backend:
    build: 
      context: .. 
      dockerfile: .devcontainer/Dockerfile 
    volumes: 
      - ..:/workspace:cached
    ports: 
      - "3000:3000"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Thalca090511!
      POSTGRES_DB: thalca-hub-db-staging

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Thalca090511!
      POSTGRES_DB: thalca-hub-db-staging
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: