services:
  backend:
    build: 
      context: .. 
      dockerfile: Dockerfile 
    command: ["/usr/local/bin/wait-for-db.sh"] 
    ports: 
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ../.env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: