version: '3.9'

services:
  backend:
    build: 
      context: .. 
      dockerfile: .devcontainer/Dockerfile 
    volumes: 
      - ..:/workspace:cached
    ports: 
      - "3000:3000"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
